#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bcftools
Version  : 1.12
Release  : 4
URL      : https://github.com/samtools/bcftools/releases/download/1.12/bcftools-1.12.tar.bz2
Source0  : https://github.com/samtools/bcftools/releases/download/1.12/bcftools-1.12.tar.bz2
Summary  : C library for high-throughput sequencing data formats
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-3.0 MIT
Requires: bcftools-bin = %{version}-%{release}
Requires: bcftools-libexec = %{version}-%{release}
Requires: bcftools-license = %{version}-%{release}
Requires: bcftools-man = %{version}-%{release}
BuildRequires : pkgconfig(htslib)

%description
BCFtools implements utilities for variant calling (in conjunction with
SAMtools) and manipulating VCF and BCF files.  The program is intended
to replace the Perl-based tools from vcftools.

%package bin
Summary: bin components for the bcftools package.
Group: Binaries
Requires: bcftools-libexec = %{version}-%{release}
Requires: bcftools-license = %{version}-%{release}

%description bin
bin components for the bcftools package.


%package libexec
Summary: libexec components for the bcftools package.
Group: Default
Requires: bcftools-license = %{version}-%{release}

%description libexec
libexec components for the bcftools package.


%package license
Summary: license components for the bcftools package.
Group: Default

%description license
license components for the bcftools package.


%package man
Summary: man components for the bcftools package.
Group: Default

%description man
man components for the bcftools package.


%prep
%setup -q -n bcftools-1.12
cd %{_builddir}/bcftools-1.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1625202449
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --with-htslib=system
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1625202449
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bcftools
cp %{_builddir}/bcftools-1.12/LICENSE %{buildroot}/usr/share/package-licenses/bcftools/5bcab80442b3e0dfbed363599edde1c85df6b396
cp %{_builddir}/bcftools-1.12/htslib-1.12/LICENSE %{buildroot}/usr/share/package-licenses/bcftools/a00a4c74a82119045d0edfe1743ee781752b07e2
cp %{_builddir}/bcftools-1.12/htslib-1.12/htscodecs/LICENSE.md %{buildroot}/usr/share/package-licenses/bcftools/6c4957c5b4497597ff61a6a6cef7b08eacbc7731
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bcftools
/usr/bin/color-chrs.pl
/usr/bin/gff2gff.py
/usr/bin/guess-ploidy.py
/usr/bin/plot-roh.py
/usr/bin/plot-vcfstats
/usr/bin/run-roh.pl
/usr/bin/vcfutils.pl

%files libexec
%defattr(-,root,root,-)
/usr/libexec/bcftools/GTisec.so
/usr/libexec/bcftools/GTsubset.so
/usr/libexec/bcftools/ad-bias.so
/usr/libexec/bcftools/add-variantkey.so
/usr/libexec/bcftools/af-dist.so
/usr/libexec/bcftools/allele-length.so
/usr/libexec/bcftools/check-ploidy.so
/usr/libexec/bcftools/check-sparsity.so
/usr/libexec/bcftools/color-chrs.so
/usr/libexec/bcftools/contrast.so
/usr/libexec/bcftools/counts.so
/usr/libexec/bcftools/dosage.so
/usr/libexec/bcftools/fill-AN-AC.so
/usr/libexec/bcftools/fill-from-fasta.so
/usr/libexec/bcftools/fill-tags.so
/usr/libexec/bcftools/fixploidy.so
/usr/libexec/bcftools/fixref.so
/usr/libexec/bcftools/frameshifts.so
/usr/libexec/bcftools/guess-ploidy.so
/usr/libexec/bcftools/gvcfz.so
/usr/libexec/bcftools/impute-info.so
/usr/libexec/bcftools/indel-stats.so
/usr/libexec/bcftools/isecGT.so
/usr/libexec/bcftools/mendelian.so
/usr/libexec/bcftools/missing2ref.so
/usr/libexec/bcftools/parental-origin.so
/usr/libexec/bcftools/prune.so
/usr/libexec/bcftools/remove-overlaps.so
/usr/libexec/bcftools/scatter.so
/usr/libexec/bcftools/setGT.so
/usr/libexec/bcftools/smpl-stats.so
/usr/libexec/bcftools/split-vep.so
/usr/libexec/bcftools/split.so
/usr/libexec/bcftools/tag2tag.so
/usr/libexec/bcftools/trio-dnm2.so
/usr/libexec/bcftools/trio-stats.so
/usr/libexec/bcftools/trio-switch-rate.so
/usr/libexec/bcftools/variantkey-hex.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bcftools/5bcab80442b3e0dfbed363599edde1c85df6b396
/usr/share/package-licenses/bcftools/6c4957c5b4497597ff61a6a6cef7b08eacbc7731
/usr/share/package-licenses/bcftools/a00a4c74a82119045d0edfe1743ee781752b07e2

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bcftools.1
