#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : bcftools
Version  : 1.20
Release  : 5
URL      : https://github.com/samtools/bcftools/releases/download/1.20/bcftools-1.20.tar.bz2
Source0  : https://github.com/samtools/bcftools/releases/download/1.20/bcftools-1.20.tar.bz2
Summary  : C library for high-throughput sequencing data formats
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: bcftools-bin = %{version}-%{release}
Requires: bcftools-libexec = %{version}-%{release}
Requires: bcftools-license = %{version}-%{release}
Requires: bcftools-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : pkgconfig(htslib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
BCFtools implements utilities for variant calling (in conjunction with
SAMtools) and manipulating VCF and BCF files.  The program is intended
to replace the Perl-based tools from vcftools.

%package bin
Summary: bin components for the bcftools package.
Group: Binaries
Requires: bcftools-libexec = %{version}-%{release}
Requires: bcftools-license = %{version}-%{release}

%description bin
bin components for the bcftools package.


%package libexec
Summary: libexec components for the bcftools package.
Group: Default
Requires: bcftools-license = %{version}-%{release}

%description libexec
libexec components for the bcftools package.


%package license
Summary: license components for the bcftools package.
Group: Default

%description license
license components for the bcftools package.


%package man
Summary: man components for the bcftools package.
Group: Default

%description man
man components for the bcftools package.


%prep
%setup -q -n bcftools-1.20
cd %{_builddir}/bcftools-1.20
pushd ..
cp -a bcftools-1.20 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719952818
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-htslib=system
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-htslib=system
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719952818
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bcftools
cp %{_builddir}/bcftools-%{version}/htslib-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/bcftools/541760bf26f52ef94859789c9e91c4b2b0218baa || :
cp %{_builddir}/bcftools-%{version}/htslib-%{version}/htscodecs/LICENSE.md %{buildroot}/usr/share/package-licenses/bcftools/6c4957c5b4497597ff61a6a6cef7b08eacbc7731 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/bcftools
/usr/bin/bcftools
/usr/bin/color-chrs.pl
/usr/bin/gff2gff.py
/usr/bin/guess-ploidy.py
/usr/bin/plot-roh.py
/usr/bin/plot-vcfstats
/usr/bin/run-roh.pl
/usr/bin/vcfutils.pl

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/bcftools/GTisec.so
/V3/usr/libexec/bcftools/GTsubset.so
/V3/usr/libexec/bcftools/ad-bias.so
/V3/usr/libexec/bcftools/add-variantkey.so
/V3/usr/libexec/bcftools/af-dist.so
/V3/usr/libexec/bcftools/allele-length.so
/V3/usr/libexec/bcftools/check-ploidy.so
/V3/usr/libexec/bcftools/check-sparsity.so
/V3/usr/libexec/bcftools/color-chrs.so
/V3/usr/libexec/bcftools/contrast.so
/V3/usr/libexec/bcftools/counts.so
/V3/usr/libexec/bcftools/dosage.so
/V3/usr/libexec/bcftools/fill-AN-AC.so
/V3/usr/libexec/bcftools/fill-from-fasta.so
/V3/usr/libexec/bcftools/fill-tags.so
/V3/usr/libexec/bcftools/fixploidy.so
/V3/usr/libexec/bcftools/fixref.so
/V3/usr/libexec/bcftools/frameshifts.so
/V3/usr/libexec/bcftools/guess-ploidy.so
/V3/usr/libexec/bcftools/gvcfz.so
/V3/usr/libexec/bcftools/impute-info.so
/V3/usr/libexec/bcftools/indel-stats.so
/V3/usr/libexec/bcftools/isecGT.so
/V3/usr/libexec/bcftools/mendelian2.so
/V3/usr/libexec/bcftools/missing2ref.so
/V3/usr/libexec/bcftools/parental-origin.so
/V3/usr/libexec/bcftools/prune.so
/V3/usr/libexec/bcftools/remove-overlaps.so
/V3/usr/libexec/bcftools/scatter.so
/V3/usr/libexec/bcftools/setGT.so
/V3/usr/libexec/bcftools/smpl-stats.so
/V3/usr/libexec/bcftools/split-vep.so
/V3/usr/libexec/bcftools/split.so
/V3/usr/libexec/bcftools/tag2tag.so
/V3/usr/libexec/bcftools/trio-dnm2.so
/V3/usr/libexec/bcftools/trio-stats.so
/V3/usr/libexec/bcftools/trio-switch-rate.so
/V3/usr/libexec/bcftools/variant-distance.so
/V3/usr/libexec/bcftools/variantkey-hex.so
/usr/libexec/bcftools/GTisec.so
/usr/libexec/bcftools/GTsubset.so
/usr/libexec/bcftools/ad-bias.so
/usr/libexec/bcftools/add-variantkey.so
/usr/libexec/bcftools/af-dist.so
/usr/libexec/bcftools/allele-length.so
/usr/libexec/bcftools/check-ploidy.so
/usr/libexec/bcftools/check-sparsity.so
/usr/libexec/bcftools/color-chrs.so
/usr/libexec/bcftools/contrast.so
/usr/libexec/bcftools/counts.so
/usr/libexec/bcftools/dosage.so
/usr/libexec/bcftools/fill-AN-AC.so
/usr/libexec/bcftools/fill-from-fasta.so
/usr/libexec/bcftools/fill-tags.so
/usr/libexec/bcftools/fixploidy.so
/usr/libexec/bcftools/fixref.so
/usr/libexec/bcftools/frameshifts.so
/usr/libexec/bcftools/guess-ploidy.so
/usr/libexec/bcftools/gvcfz.so
/usr/libexec/bcftools/impute-info.so
/usr/libexec/bcftools/indel-stats.so
/usr/libexec/bcftools/isecGT.so
/usr/libexec/bcftools/mendelian2.so
/usr/libexec/bcftools/missing2ref.so
/usr/libexec/bcftools/parental-origin.so
/usr/libexec/bcftools/prune.so
/usr/libexec/bcftools/remove-overlaps.so
/usr/libexec/bcftools/scatter.so
/usr/libexec/bcftools/setGT.so
/usr/libexec/bcftools/smpl-stats.so
/usr/libexec/bcftools/split-vep.so
/usr/libexec/bcftools/split.so
/usr/libexec/bcftools/tag2tag.so
/usr/libexec/bcftools/trio-dnm2.so
/usr/libexec/bcftools/trio-stats.so
/usr/libexec/bcftools/trio-switch-rate.so
/usr/libexec/bcftools/variant-distance.so
/usr/libexec/bcftools/variantkey-hex.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bcftools/541760bf26f52ef94859789c9e91c4b2b0218baa
/usr/share/package-licenses/bcftools/6c4957c5b4497597ff61a6a6cef7b08eacbc7731

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bcftools.1
